name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - notebook=6.5.2
  - jupyterlab
  - seaborn=0.12.2
  - pandas=1.2.3
  - pip=22.3.1
  - pandas-profiling=3.6.2
  - pyarrow=10.0.1
  - pip:
      - wandb==0.13.7