name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.3.1
  - requests=2.28.1
  - mlflow=2.0.1
  - pip:
      - wandb==0.13.7
      - git+https://github.com/Mamoutou7/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components